<?php
/**
 * Setup API — for automated setup wizard actions
 * - save_config: write config.php from form (creates DB if missing)
 * - create_db: try to create database if not exists
 * - test: test connection only
 *
 * No auth — used during first-time setup before app is installed.
 */
header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['ok' => false, 'msg' => 'Method not allowed']);
    exit;
}

$action = $_POST['action'] ?? '';

function jsonResp(bool $ok, string $msg, array $extra = []): never {
    echo json_encode(array_merge(['ok' => $ok, 'msg' => $msg], $extra));
    exit;
}

$cfgPath = dirname(__DIR__) . '/config.php';

/* ── test ── */
if ($action === 'test') {
    $host = trim($_POST['host'] ?? 'localhost');
    $user = trim($_POST['user'] ?? 'root');
    $pass = $_POST['pass'] ?? '';
    $name = trim($_POST['dbname'] ?? 'php_mis_brgy');
    if (!$host || !$user || !$name) {
        jsonResp(false, 'Host, user, and database name are required.');
    }
    mysqli_report(MYSQLI_REPORT_OFF);
    $conn = @new mysqli($host, $user, $pass, $name);
    if ($conn->connect_errno) {
        $err = $conn->connect_error;
        $code = $conn->connect_errno;
        if ($code === 1049) {
            jsonResp(false, 'Database "' . $name . '" does not exist. Click "Save & Install" to create it automatically.', ['create_db' => true]);
        }
        jsonResp(false, 'Connection failed: ' . $err);
    }
    $conn->set_charset('utf8mb4');
    $conn->close();
    jsonResp(true, 'Connection successful.');
}

/* ── create_db ── */
if ($action === 'create_db') {
    $host = trim($_POST['host'] ?? 'localhost');
    $user = trim($_POST['user'] ?? 'root');
    $pass = $_POST['pass'] ?? '';
    $name = trim($_POST['dbname'] ?? 'php_mis_brgy');
    if (!$name) {
        jsonResp(false, 'Database name is required.');
    }
    mysqli_report(MYSQLI_REPORT_OFF);
    $conn = @new mysqli($host, $user, $pass, '');
    if ($conn->connect_errno) {
        jsonResp(false, 'Cannot connect to MySQL: ' . $conn->connect_error . '. Make sure MySQL is running (e.g. start Laragon).');
    }
    $nameEsc = '`' . str_replace('`', '``', $name) . '`';
    if (!$conn->query("CREATE DATABASE IF NOT EXISTS {$nameEsc} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")) {
        jsonResp(false, 'Failed to create database: ' . $conn->error);
    }
    $conn->close();
    jsonResp(true, 'Database "' . $name . '" created successfully.');
}

/* ── save_config ── */
if ($action === 'save_config') {
    $host = trim($_POST['host'] ?? 'localhost') ?: '127.0.0.1';
    $user = trim($_POST['user'] ?? 'root') ?: 'root';
    $pass = $_POST['pass'] ?? '';
    $name = trim($_POST['dbname'] ?? 'php_mis_brgy') ?: 'php_mis_brgy';

    if (!$host || !$user || !$name) {
        jsonResp(false, 'Host, user, and database name are required.');
    }

    mysqli_report(MYSQLI_REPORT_OFF);
    $conn = @new mysqli($host, $user, $pass, '');
    if ($conn->connect_errno) {
        jsonResp(false, 'Cannot connect to MySQL. Make sure MySQL is running (e.g. Laragon → Start All).');
    }
    $nameEsc = '`' . str_replace('`', '``', $name) . '`';
    if (!$conn->query("CREATE DATABASE IF NOT EXISTS {$nameEsc} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")) {
        jsonResp(false, 'Failed to create database: ' . $conn->error);
    }
    $conn->close();

    $content = '<?php
/**
 * Configuration File — generated by Setup Wizard
 */
define(\'DB_HOST\', ' . var_export($host, true) . ');
define(\'DB_USER\', ' . var_export($user, true) . ');
define(\'DB_PASS\', ' . var_export($pass, true) . ');
define(\'DB_NAME\', ' . var_export($name, true) . ');
define(\'BASE_PATH\', dirname(__DIR__));
define(\'INCLUDES_PATH\', BASE_PATH . \'/includes\');
define(\'PUBLIC_PATH\', BASE_PATH . \'/public\');
';

    if (!is_writable(dirname($cfgPath)) && !file_exists($cfgPath)) {
        jsonResp(false, 'Cannot write config. Check folder permissions for: ' . dirname($cfgPath));
    }
    if (file_exists($cfgPath) && !is_writable($cfgPath)) {
        jsonResp(false, 'config.php exists but is not writable. Check file permissions.');
    }
    if (file_put_contents($cfgPath, $content) === false) {
        jsonResp(false, 'Failed to write config.php.');
    }
    jsonResp(true, 'Configuration saved. Database created. You can continue setup.');
}

jsonResp(false, 'Unknown action.');
